# Port Metadata
PORTNAME =          mruby
PORTVERSION =       3.2.0

MAINTAINER =        X
LICENSE =           MIT
SHORT_DESC =        Lightweight Ruby

# No dependencies beyond the base system.
DEPENDENCIES =

# What files we need to download, and where from.
GIT_REPOSITORY =    https://github.com/mruby/mruby.git
GIT_BRANCH =		master

TARGET =            libmruby.a
HDR_DIRECTORY =     build/$(KOS_ARCH)/include
HDR_INSTDIR =       mruby

# KOS Distributed extras (to be copied into the build tree)
KOS_DISTFILES =     KOSMakefile.mk

include ${KOS_PORTS}/scripts/kos-ports.mk
