# Port Metadata
PORTNAME =        libjimtcl
PORTVERSION =    1.0.0

MAINTAINER =    Spencer (@spencerelliott)
LICENSE =       FreeBSD
SHORT_DESC =    An open-source, small footprint implementation of Tcl

# What files we need to download, and where from.
GIT_REPOSITORY =    https://github.com/msteveb/jimtcl.git

TARGET =        libjim.a
INSTALLED_HDRS =    jim.h jim-win32compat.h jim-config.h
HDR_INSTDIR =        jimtcl

# KOS Distributed extras (to be copied into the build tree)
KOS_DISTFILES =		KOSMakefile.mk

include ${KOS_PORTS}/scripts/kos-ports.mk
