# Port Metadata
PORTNAME =          libfastmem
PORTVERSION =       1.0.0

MAINTAINER =        SiZiOUS <sizious@gmail.com>
LICENSE =           LGPLv2.1
SHORT_DESC =        Very optimized set of memory manipulation functions

DEPENDENCIES =      

# What files we need to download, and where from.
GIT_REPOSITORY =    https://github.com/sega-dreamcast/libfastmem.git

TARGET =            libfastmem.a
INSTALLED_HDRS =    include/fastmem.h
HDR_INSTDIR =       fastmem

# KOS Distributed extras (to be copied into the build tree)
KOS_DISTFILES =	    KOSMakefile.mk

include ${KOS_PORTS}/scripts/kos-ports.mk
